import type { Config } from 'tailwindcss'

export default {
  // Empty — @nuxtjs/tailwindcss auto-scans all layer templates via Nuxt hooks.
  content: [],
  theme: {
    extend: {
      colors: {
        primary:                    '#6d46b1',
        'on-primary':               '#ffffff',
        'primary-container':        '#5b21b6',
        'on-primary-container':     '#ede9fe',
        'primary-fixed':            '#f5f3ff',
        'primary-fixed-dim':        '#c4b5fd',
        'on-primary-fixed':         '#2e1065',
        'on-primary-fixed-variant': '#6d28d9',
        'inverse-primary':          '#c4b5fd',
        'surface-tint':             '#7c3aed',

        secondary:                    '#5b5777',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#e8e4f8',
        'on-secondary-container':     '#4a4668',
        'secondary-fixed':            '#e8e4f8',
        'secondary-fixed-dim':        '#cac4e0',
        'on-secondary-fixed':         '#1d1a2e',
        'on-secondary-fixed-variant': '#444061',

        surface:                     '#faf9ff',
        'surface-bright':            '#faf9ff',
        background:                  '#faf9ff',
        'surface-dim':               '#d9d6e6',
        'surface-variant':           '#e6e0f0',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f3f0fa',
        'surface-container':         '#ede9f7',
        'surface-container-high':    '#e7e3f4',
        'surface-container-highest': '#e2deee',
        'inverse-surface':           '#2e2b3b',
        'inverse-on-surface':        '#f1eeff',

        'on-surface':         '#1c1b25',
        'on-background':      '#1c1b25',
        'on-surface-variant': '#48444f',
        'outline-variant':    '#cac4d6',
        outline:              '#79747e',

        tertiary:                    '#481f00',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#693100',
        'on-tertiary-container':     '#ec9961',
        'tertiary-fixed':            '#ffdbc7',
        'tertiary-fixed-dim':        '#ffb688',
        'on-tertiary-fixed':         '#311300',
        'on-tertiary-fixed-variant': '#713705',
        error:               '#ba1a1a',
        'on-error':          '#ffffff',
        'error-container':   '#ffdad6',
        'on-error-container':'#93000a',
      },
      spacing: {
        'container-max':   '80rem',
        gutter:            '2rem',
        'stack-sm':        '1rem',
        'stack-md':        '2rem',
        'stack-lg':        '4rem',
        'section-padding': 'clamp(2.5rem, 6vw + 1rem, 8rem)',
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        body:    ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        'body-md':    ['0.875rem',  { lineHeight: '1.5',   fontWeight: '400' }],
        'body-lg':    ['1.125rem',  { lineHeight: '1.625', fontWeight: '400' }],
        'label-md':   ['10px',      { lineHeight: '1', letterSpacing: '0.2em', fontWeight: '700' }],
        'nav-link':   ['0.875rem',  { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md':['1.25rem',   { lineHeight: '1.5',   fontWeight: '700' }],
        'headline-lg':['2.25rem',   { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        display:      ['4.5rem',    { lineHeight: '1.1', letterSpacing: '-0.05em', fontWeight: '700' }],
      },
    },
  },
} satisfies Config
